{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "spark-on-k8s.serviceAccountName" . }}
  labels:
    {{- include "spark-on-k8s.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "spark-on-k8s.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "spark-on-k8s.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  # this cluster role is enough to list pods and reverse proxy to them,
  # but we will need more permissions in the future to kill/submit jobs (edit)
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
{{- end }}